// packages/tooling/src/ads/refresh-skadnetwork.ts
// Usage: node packages/tooling/src/ads/refresh-skadnetwork.ts [--check]
// Rewrites packages/shell/src/config/skadnetwork-ids.ts from Google's AdMob iOS quick-start page.
// --check exits 1 when the committed list is stale (run by release:ios). Dev tooling may use the
// network; the app never does (N3 covers the app bundle, not packages/tooling).
import { existsSync, readFileSync, writeFileSync } from 'node:fs';

const SOURCE = 'https://developers.google.com/admob/ios/quick-start';
const TARGET = 'packages/shell/src/config/skadnetwork-ids.ts';
const ID = /\b[a-z0-9]{10}\.skadnetwork\b/g;

async function fetchIds(): Promise<string[]> {
  const response = await fetch(SOURCE);
  if (!response.ok) throw new Error(`${SOURCE}: HTTP ${String(response.status)}`);
  const ids = [...new Set((await response.text()).match(ID) ?? [])];
  if (ids[0] !== 'cstr6suwn9.skadnetwork' || ids.length < 40) {
    throw new Error(`unexpected page content (${String(ids.length)} ids): refusing to overwrite`);
  }
  return ids;
}

function render(ids: readonly string[]): string {
  const lines = ids.map((id) => `  '${id}',`).join('\n');
  return `// ${TARGET}\n// GENERATED by refresh-skadnetwork.ts from ${SOURCE}. Do not edit.\nexport const SKADNETWORK_IDS: readonly string[] = [\n${lines}\n];\n`;
}

async function main(isCheck: boolean): Promise<void> {
  const fresh = await fetchIds();
  const committed: readonly string[] = existsSync(TARGET)
    ? (readFileSync(TARGET, 'utf8').match(ID) ?? [])
    : [];
  const added = fresh.filter((id) => !committed.includes(id));
  const removed = committed.filter((id) => !fresh.includes(id));
  console.error(
    `skadnetwork: ${String(fresh.length)} ids, +${String(added.length)} -${String(removed.length)}`,
  );
  if (isCheck) {
    process.exitCode = added.length + removed.length === 0 ? 0 : 1;
    return;
  }
  writeFileSync(TARGET, render(fresh));
}

await main(process.argv.includes('--check'));
