// babel.config.js — generated by `npx expo customize babel.config.js`, moved to the repo root
// so the root Jest run finds it (jest-expo resolves Babel options from process.cwd()).
// Stryker workers (STRYKER_MUTATOR_WORKER) compile WITHOUT the Worklets plugin: Stryker injects helper
// functions into every mutated file, and a file-level 'worklet' directive would workletize them too
// ("stryNS_… is read-only"). Worklet transforms change no behaviour when code runs as plain JS in Jest.
module.exports = function (api) {
  const isMutationRun = process.env.STRYKER_MUTATOR_WORKER !== undefined;
  api.cache.using(() => isMutationRun);
  return {
    presets: [['babel-preset-expo', isMutationRun ? { worklets: false, reanimated: false } : {}]],
  };
};
