// packages/tooling/src/art/build-icon-paths.ts
// Turns the Toybox icon layers (icon-layers.json next to this file) into one nonzero fill path per
// icon and writes packages/shell/src/ui/icons/icon-paths.ts.
// Run from the repo root: node packages/tooling/src/art/build-icon-paths.ts [--check] (--help for more)
import { existsSync, readFileSync, writeFileSync } from 'node:fs';

import { loadHeadlessSkia } from '@e07/tooling/visual/load-headless-skia.ts';

import { failInput, readCliOrExit } from './art-cli.ts';

import type { CliSpec } from './art-cli.ts';
import type { HeadlessSkia } from '@e07/tooling/visual/load-headless-skia.ts';
import type { SkPath } from '@shopify/react-native-skia';

type IconLayer =
  | {
      readonly op: 'stroke';
      readonly width: number;
      readonly cap: 'round' | 'butt';
      readonly join: 'round';
      readonly d: string;
    }
  | { readonly op: 'fill'; readonly fillRule: 'nonzero' | 'evenodd'; readonly d: string };
type IconLayers = {
  readonly directional: readonly string[];
  readonly glyphs: Readonly<Record<string, { readonly layers: readonly IconLayer[] }>>;
};

// Numeric values of Skia's StrokeCap, StrokeJoin, FillType and PathOp enums (types-only import rule).
const CAP_BUTT = 0;
const CAP_ROUND = 1;
const JOIN_ROUND = 1;
const FILL_EVEN_ODD = 1;
const OP_UNION = 2;
const LAYERS = 'packages/tooling/src/art/icon-layers.json';
const OUT = 'packages/shell/src/ui/icons/icon-paths.ts';
const PRINT_WIDTH = 100;
const SHORT_KEY = 5;
const CLI: CliSpec = {
  command: 'node packages/tooling/src/art/build-icon-paths.ts',
  summary: `Writes ${OUT} (one nonzero fill path per icon) from ${LAYERS}. Run from the repo root.`,
  options: {
    check: {
      type: 'boolean',
      help: 'Write nothing; exit 1 when icon-paths.ts differs from the layers',
    },
  },
  notes: ['Exit codes: 0 written or current, 1 stale (--check), 2 bad input.'],
};

function layerPath(skia: HeadlessSkia, layer: IconLayer): SkPath {
  const path = skia.Path.MakeFromSVGString(layer.d);
  if (path === null) throw new Error(`Bad path data: ${layer.d}`);
  if (layer.op === 'stroke') {
    const cap = layer.cap === 'round' ? CAP_ROUND : CAP_BUTT;
    const stroked = skia.Path.Stroke(path, { width: layer.width, cap, join: JOIN_ROUND });
    if (stroked === null) throw new Error(`Stroke failed: ${layer.d}`);
    return stroked;
  }
  if (layer.fillRule === 'nonzero') return path;
  return skia.PathBuilder.MakeFromPath(path).setFillType(FILL_EVEN_ODD).build();
}

/** Union of all layers, rewritten with the nonzero rule (path ops return even-odd paths). */
export function flattenIcon(skia: HeadlessSkia, layers: readonly IconLayer[]): string {
  let union: SkPath | null = null;
  for (const layer of layers) {
    const path = layerPath(skia, layer);
    union = union === null ? path : skia.Path.MakeFromOp(union, path, OP_UNION);
    if (union === null) throw new Error('Union failed');
  }
  const winding = union === null ? null : skia.Path.AsWinding(union);
  if (winding === null) throw new Error('Winding conversion failed');
  // Two decimals on a 24-unit grid is 0.06 px at 3x: invisible, and about half the size.
  return winding
    .toSVGString()
    .replace(/-?\d*\.\d+/g, (n) => String(Math.round(Number(n) * 100) / 100));
}

/**
 * One ICON_PATHS entry, formatted the way Prettier (printWidth 100, tabWidth 2) prints it: a line
 * that fits stays whole; otherwise Prettier breaks after the key unless the key is shorter than 5.
 */
function entryLines(name: string, d: string): string[] {
  const key = /^[a-z]+$/.test(name) ? name : `'${name}'`;
  const line = `  ${key}: '${d}',`;
  const isShortKey = key.length < SHORT_KEY;
  return line.length <= PRINT_WIDTH || isShortKey ? [line] : [`  ${key}:`, `    '${d}',`];
}

function moduleText(skia: HeadlessSkia, data: IconLayers): string {
  const entries = Object.entries(data.glyphs).flatMap(([name, glyph]) =>
    entryLines(name, flattenIcon(skia, glyph.layers)),
  );
  return [
    '// packages/shell/src/ui/icons/icon-paths.ts',
    '// GENERATED by packages/tooling/src/art/build-icon-paths.ts from icon-layers.json. Do not edit.',
    '/** Every Shell icon: one SVG path on a 24 x 24 grid, nonzero fill, single colour (tintColor). */',
    'export const ICON_PATHS = {',
    ...entries,
    '} as const;',
    '',
    'export type IconName = keyof typeof ICON_PATHS;',
    '',
    '/** Icons that point along the reading direction flip in RTL. */',
    'export const DIRECTIONAL_ICONS: ReadonlySet<IconName> = new Set<IconName>([',
    ...data.directional.map((name) => `  '${name}',`),
    ']);',
    '',
  ].join('\n');
}

async function main(): Promise<void> {
  const values = readCliOrExit(CLI);
  if (values === null) return;
  if (!existsSync(LAYERS)) {
    failInput(CLI, `${LAYERS} is missing (run from the repo root after copying the art templates)`);
    return;
  }
  const skia = await loadHeadlessSkia();
  const data = JSON.parse(readFileSync(LAYERS, 'utf8')) as IconLayers;
  const text = moduleText(skia, data);
  if (values['check'] === true) {
    const isStale = !existsSync(OUT) || readFileSync(OUT, 'utf8') !== text;
    if (isStale) {
      console.error(`${OUT} is stale: run node packages/tooling/src/art/build-icon-paths.ts`);
      process.exitCode = 1;
    }
    return;
  }
  writeFileSync(OUT, text);
  console.log(`wrote ${OUT} (${String(Object.keys(data.glyphs).length)} icons)`);
}

await main();
