// packages/tooling/src/art/render-art.ts
// Renders a game's app icon (light, dark, tinted) and splash logos (light, dark) with headless
// Skia from its Toybox logo (apps/<game>/src/art/logo-art.ts) and palette (src/theme/palette.ts).
// Writes apps/<game>/assets/generated/*.png and the game's splash grounds in
// packages/shell/src/config/splash-grounds.ts (all committed). --check re-renders in memory and
// exits 1 when a committed file is stale.
// Run from the repo root: node packages/tooling/src/art/render-art.ts --app line-siege [--check]
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { drawLogoArt, drawLogoTile } from '@e07/shell/art/draw-logo.ts';
import { logoOps } from '@e07/shell/art/logo-art.ts';
import { SHELL_COLORS } from '@e07/shell/theme/shell-colors.ts';
import { loadHeadlessSkia } from '@e07/tooling/visual/load-headless-skia.ts';

import { failInput, readCliOrExit } from './art-cli.ts';

import type { CliSpec, CliValues } from './art-cli.ts';
import type { SkiaApi } from '@e07/shell/art/draw-logo.ts';
import type { LogoArt } from '@e07/shell/art/logo-art.ts';
import type { ColorScheme, ColorTokens, Palette } from '@e07/shell/theme/theme-types.ts';

type Variant = 'light' | 'dark' | 'tinted' | 'splash';
type Ground = { readonly light: string; readonly dark: string };
type Output = { readonly file: string; readonly variant: Variant; readonly scheme: ColorScheme };

const GROUNDS_FILE = 'packages/shell/src/config/splash-grounds.ts';
const CLI: CliSpec = {
  command: 'node packages/tooling/src/art/render-art.ts',
  summary: `Renders a game's app icon (light, dark, tinted) and splash logos (light, dark) into apps/<game-id>/assets/generated/ and its splash grounds into ${GROUNDS_FILE}, from its LOGO_ART and PALETTE. Run from the repo root.`,
  options: {
    app: {
      type: 'string',
      value: '<game-id>',
      isRequired: true,
      help: 'The game to render, e.g. line-siege',
    },
    check: {
      type: 'boolean',
      help: 'Write nothing; exit 1 when a committed PNG or the grounds are stale',
    },
  },
  notes: [
    'Exit codes: 0 written or current, 1 stale (--check), 2 bad input (no --app, unknown game).',
  ],
};
const GROUNDS_HEADER = [
  '// packages/shell/src/config/splash-grounds.ts',
  '// GENERATED by packages/tooling/src/art/render-art.ts. Do not edit: rerun it after a palette change.',
  "import type { SplashColors } from './art-config.ts';",
  '',
  "/** Each drawn game's S1 ground (its palette background), light and dark, for the native splash. */",
  'export const SPLASH_GROUNDS: Readonly<Partial<Record<string, SplashColors>>> = {',
];
const SIZE = 1024;
/** Apple: keep the glyph inside the central area; Toybox uses 62 % of the icon. */
const GLYPH = 0.62;
/** The splash image is shown 200 pt wide (expo-splash-screen imageWidth). */
const SPLASH_PT = 200;
/** S1 logo tile: 152 pt, 4 pt edge, 7 pt ring, -6 degrees. */
const SPLASH_TILE = { size: 152, edge: 4, ring: 7, rotateDeg: -6 } as const;
const OUTPUTS: readonly Output[] = [
  { file: 'icon-light.png', variant: 'light', scheme: 'light' },
  { file: 'icon-dark.png', variant: 'dark', scheme: 'dark' },
  { file: 'icon-tinted.png', variant: 'tinted', scheme: 'dark' },
  { file: 'splash-logo.png', variant: 'splash', scheme: 'light' },
  { file: 'splash-logo-dark.png', variant: 'splash', scheme: 'dark' },
];
/** Rec. 709 luma: the tinted icon must be grayscale. */
const GRAYSCALE = [
  0.2126, 0.7152, 0.0722, 0, 0, 0.2126, 0.7152, 0.0722, 0, 0, 0.2126, 0.7152, 0.0722, 0, 0, 0, 0, 0,
  1, 0,
];

type Frame = {
  readonly skia: SkiaApi;
  readonly logo: LogoArt;
  readonly colors: ColorTokens;
  readonly scheme: ColorScheme;
};

function opsFor(frame: Frame): ReturnType<typeof logoOps> {
  const shell = SHELL_COLORS[frame.scheme];
  return logoOps(frame.logo, { pop: frame.colors.pop, toyInk: shell.toyInk, white: shell.cut });
}

/** Dark and tinted icons: the "cut" logo tile (toy-ink edge, white ring), untilted, 62 % wide. */
function iconTileSpec(frame: Frame): Parameters<typeof drawLogoTile>[2]['spec'] {
  const shell = SHELL_COLORS[frame.scheme];
  const tile = (SIZE * GLYPH) / (1 + (SPLASH_TILE.ring * 2) / SPLASH_TILE.size);
  return {
    size: tile,
    fill: frame.colors.primary,
    edge: shell.toyInk,
    edgeWidth: (tile * SPLASH_TILE.edge) / SPLASH_TILE.size,
    ring: (tile * SPLASH_TILE.ring) / SPLASH_TILE.size,
    ringColor: shell.cut,
    rotateDeg: 0,
  };
}

function splashSpec(frame: Frame): Parameters<typeof drawLogoTile>[2]['spec'] {
  const px = SIZE / SPLASH_PT;
  return {
    size: SPLASH_TILE.size * px,
    fill: frame.colors.primary,
    edge: frame.colors.border,
    edgeWidth: SPLASH_TILE.edge * px,
    ring: SPLASH_TILE.ring * px,
    ringColor: SHELL_COLORS[frame.scheme].cut,
    rotateDeg: SPLASH_TILE.rotateDeg,
  };
}

function draw(frame: Frame, variant: Variant, canvas: Parameters<typeof drawLogoArt>[1]): void {
  const { skia } = frame;
  const center = SIZE / 2;
  if (variant === 'light') {
    // Opaque, full bleed: the accent is the tile; iOS masks the corners.
    canvas.drawColor(skia.Color(frame.colors.primary));
    canvas.translate((SIZE * (1 - GLYPH)) / 2, (SIZE * (1 - GLYPH)) / 2);
    drawLogoArt(skia, canvas, { ops: opsFor(frame), size: SIZE * GLYPH });
    return;
  }
  if (variant === 'tinted') canvas.drawColor(skia.Color(frame.colors.background));
  const spec = variant === 'splash' ? splashSpec(frame) : iconTileSpec(frame);
  drawLogoTile(skia, canvas, { ops: opsFor(frame), spec, cx: center, cy: center });
}

function renderOne(frame: Frame, output: Output): Uint8Array {
  const surface = frame.skia.Surface.Make(SIZE, SIZE);
  if (surface === null) throw new Error('No offscreen surface');
  const canvas = surface.getCanvas();
  canvas.clear(frame.skia.Color('transparent'));
  if (output.variant === 'tinted') {
    const gray = frame.skia.Paint();
    gray.setColorFilter(frame.skia.ColorFilter.MakeMatrix(GRAYSCALE));
    canvas.saveLayer(gray);
  }
  draw(frame, output.variant, canvas);
  if (output.variant === 'tinted') canvas.restore();
  surface.flush();
  return surface.makeImageSnapshot().encodeToBytes();
}

/** splash-grounds.ts with this game's entry set, keys sorted and quoted the way Prettier prints them. */
async function groundsText(app: string, ground: Ground): Promise<string> {
  const grounds: Record<string, Ground> = {};
  if (existsSync(GROUNDS_FILE)) {
    const { SPLASH_GROUNDS: current } = await import('@e07/shell/config/splash-grounds.ts');
    for (const [id, value] of Object.entries(current)) {
      if (value !== undefined) grounds[id] = value;
    }
  }
  grounds[app] = ground;
  const entries = Object.keys(grounds)
    .sort()
    .map((id) => {
      const key = /^[a-z][a-z0-9]*$/.test(id) ? id : `'${id}'`;
      return `  ${key}: { light: '${grounds[id]?.light ?? ''}', dark: '${grounds[id]?.dark ?? ''}' },`;
    });
  return [...GROUNDS_HEADER, ...entries, '};', ''].join('\n');
}

/** Writes this game's splash grounds (or, with --check, reports whether they are current). */
async function syncGrounds(app: string, palette: Palette, isCheck: boolean): Promise<boolean> {
  const ground = {
    light: palette.standard.light.background,
    dark: palette.standard.dark.background,
  };
  const text = await groundsText(app, ground);
  if (isCheck) return existsSync(GROUNDS_FILE) && readFileSync(GROUNDS_FILE, 'utf8') === text;
  writeFileSync(GROUNDS_FILE, text);
  console.log(`wrote ${GROUNDS_FILE} (${app})`);
  return true;
}

type GameArtInput = { readonly logo: LogoArt; readonly palette: Palette };

/** The game's LOGO_ART and PALETTE from its app workspace, or what is missing, in words. */
async function loadGame(app: string): Promise<GameArtInput | string> {
  const logoFile = join('apps', app, 'src', 'art', 'logo-art.ts');
  const paletteFile = join('apps', app, 'src', 'theme', 'palette.ts');
  if (!existsSync(logoFile)) return `${logoFile} is missing: draw the game's LOGO_ART first`;
  if (!existsSync(paletteFile)) return `${paletteFile} is missing: write the game's PALETTE first`;
  const { LOGO_ART: logo } = (await import(`@e07/${app}/art/logo-art.ts`)) as {
    readonly LOGO_ART?: LogoArt;
  };
  const { PALETTE: palette } = (await import(`@e07/${app}/theme/palette.ts`)) as {
    readonly PALETTE?: Palette;
  };
  if (logo === undefined) return `${logoFile} must export LOGO_ART`;
  if (palette === undefined) return `${paletteFile} must export PALETTE`;
  return { logo, palette };
}

/** The --app value when it names an existing game; otherwise prints the error and gives null. */
function appFrom(values: CliValues): string | null {
  const app = typeof values['app'] === 'string' ? values['app'] : '';
  if (!/^[a-z][a-z0-9-]*$/.test(app)) {
    failInput(CLI, 'pass --app <game-id>, e.g. --app line-siege');
    return null;
  }
  if (!existsSync(join('apps', app, 'src'))) {
    failInput(
      CLI,
      `apps/${app}/src does not exist (run from the repo root with an existing game id)`,
    );
    return null;
  }
  return app;
}

type RenderJob = {
  readonly skia: SkiaApi;
  readonly app: string;
  readonly game: GameArtInput;
  readonly isCheck: boolean;
};

/** Renders the five PNGs; writes them, or (check) returns the paths whose bytes differ. */
function renderOutputs(job: RenderJob): string[] {
  const { skia, app, game, isCheck } = job;
  const outDir = join('apps', app, 'assets', 'generated');
  mkdirSync(outDir, { recursive: true });
  const stale: string[] = [];
  for (const output of OUTPUTS) {
    const colors = game.palette.standard[output.scheme];
    const png = renderOne({ skia, logo: game.logo, colors, scheme: output.scheme }, output);
    const path = join(outDir, output.file);
    if (!isCheck) {
      writeFileSync(path, png);
      console.log(`wrote ${path}`);
    } else if (!existsSync(path) || !Buffer.from(png).equals(readFileSync(path))) {
      stale.push(path);
    }
  }
  return stale;
}

async function main(): Promise<void> {
  const values = readCliOrExit(CLI);
  const app = values === null ? null : appFrom(values);
  if (values === null || app === null) return;
  const isCheck = values['check'] === true;
  const game = await loadGame(app);
  if (typeof game === 'string') {
    failInput(CLI, game);
    return;
  }
  // The headless build declares its own copy of the Skia types; the runtime API is the same.
  const skia = (await loadHeadlessSkia()) as unknown as SkiaApi;
  const stale = renderOutputs({ skia, app, game, isCheck });
  if (!(await syncGrounds(app, game.palette, isCheck))) stale.push(GROUNDS_FILE);
  if (stale.length > 0) {
    console.error(`Stale generated art (run without --check and commit):\n${stale.join('\n')}`);
    process.exitCode = 1;
  }
}

await main();
