// packages/game-kit/src/contract/levels.ts
import type { MessageId } from '@e07/game-kit/contract/messages.ts';

/**
 * Spec 8.1: puzzle games rate against par, score games against thresholds [win, two, three]:
 * thresholds[0] is the lowest score a win can have (0 when the win is not score-based, as in
 * Line Siege), two and three stars need thresholds[1] and thresholds[2].
 */
export type StarRule =
  | { readonly kind: 'par'; readonly par: number }
  | { readonly kind: 'score'; readonly thresholds: readonly [number, number, number] };

/** One shipped level: generated by tooling, solver-checked, committed as JSON. */
export type LevelEntry = {
  /** 1-based and global across packs ("Level 12"). */
  readonly level: number;
  readonly seed: number;
  readonly difficulty: number;
  readonly stars: StarRule;
};

/** Spec S8: packs unlock by stars collected. */
export type LevelPack = {
  readonly id: string;
  readonly nameId: MessageId;
  readonly firstLevel: number;
  readonly levelCount: number;
  readonly starsToUnlock: number;
};

/**
 * A solver's answer. `solved` carries the winning line, its length (par for an exact solver) and
 * the state the line ends in, so a score-rated plan reads the score without a replay.
 * `unsolvable` means the whole space was searched; `budget-exceeded` only that the solver gave up.
 */
export type SolveResult<TState, TMove> =
  | {
      readonly kind: 'solved';
      readonly par: number;
      readonly line: readonly TMove[];
      readonly final: TState;
    }
  | { readonly kind: 'unsolvable' }
  | { readonly kind: 'budget-exceeded' };

/**
 * Proves a level winnable: an exact search (par) or, for games that draw their future from the
 * RNG, a witness (createWitnessSolver). Tooling and tests only, never at runtime.
 */
export type Solver<TState, TMove> = {
  readonly solve: (start: TState, maxNodes: number) => SolveResult<TState, TMove>;
};

/** Spec 10 LEVELS, 8.2 modes, 8.3 daily. The generator is GameEngine.create(seed, difficulty). */
export type LevelsSpec<TState, TMove> = {
  /** Difficulty curve; tooling regenerates the pack-<n>.json tables from it. */
  readonly difficultyFor: (level: number) => number;
  readonly packs: readonly LevelPack[];
  /** From src/levels/pack-<n>.json, concatenated; one entry per shipped level. */
  readonly table: readonly LevelEntry[];
  readonly solver: Solver<TState, TMove> | null;
  readonly daily:
    | { readonly kind: 'none' }
    | { readonly kind: 'daily'; readonly difficulty: number; readonly salt: number };
  /**
   * { kind: 'endless', difficulty: ENDLESS_DIFFICULTY } exactly when game.config.ts has
   * modes.endless true: the run is create(freshSeed, 100) and never won.
   */
  readonly endless:
    { readonly kind: 'none' } | { readonly kind: 'endless'; readonly difficulty: number };
};
